### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined thrown in some cases

### ISSUE THREAD

**Issue by msrose** [tophat/with-immutable-props-to-js#32]
For some reason, using this package broke SSR for one of Top Hat's internal projects (fe-marketplace), which is strange because the code existed almost in the exact same form in that project before being factored out. Need to investigate why that happened and figure out if there's any configuration we need within this package to support SSR. cc @tgrant59 for any more context.

**Comment by sanchitgera** [comment]
Did some more investigation on this. I don't think this has to do _specifically_ with SSR. Loading with-immutable-props fails with this error: 
```ReferenceError: regeneratorRuntime is not defined```
This usually only happens if the polyfill for generators is not imported. Though I don't think that is the cause here, since we are importing `babel-polyfill`  which provides the `regenerator-runtime`. I'm guessing there is a version mismatch somewhere. 🤷‍♂️ 
Will update when I have something more.

**Comment by msrose** [comment]
Awesome, thanks for the investigation @sanchitgera. Good to hear that this probably doesn't have anything to do with SSR, I'm going to rename the issue title.

**Comment by msrose** [comment]
Addressed in #39
